# Generated by Django 5.0.7 on 2024-08-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_profile_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantedtree',
            name='location',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
